### ISSUE TITLE
[Roadmap] DGL support checklist

### ISSUE THREAD

**Issue by xptree** [tencent-alchemy/Alchemy#5]
We should support DGL, which is another GNN library. Here is the release plan. The tentative release date is 07/31/2019, before the contest enters phase two.

## [Feature] DGL dataloader

Release a DGL dataloader for reading the Alchemy dataset.

- [x]  DGL-style Alchemy dataloader.
- [x] README for DGL dataloader

## [Feature] DGL MPNN model

Release a DGL MPNN model as what we have done for PyG. [MPNN](https://arxiv.org/abs/1704.01212) model is GGNN + set2set, SchNet and MGCN are also included:

- [x] DGL [GGNN](https://arxiv.org/abs/1511.05493) implementation
- [x] DGL [set2set](https://arxiv.org/abs/1511.06391) implementation (PR dmlc/dgl#669)
- [x] DGL [SchNet](https://arxiv.org/abs/1706.08566) implementation
- [x] DGL [MGCN](https://arxiv.org/abs/1906.11081) implementation

**Comment by yzh119** [comment]
Hi, glad to hear that you would like to support DGL. We have a plan for graph pooling that supports set2set, you could find our PR [here](https://github.com/dmlc/dgl/pull/669).

**Comment by xptree** [comment]
@yzh119 Super! I have added the PR link to our release plan. We can help check if the DGL set2set performance is comparable to the PyG implementation. BTW, when do you plan to release the set2set implementation?

**Comment by yzh119** [comment]
@xptree We are trying to complete this PR within this week. But it would take longer(about two months) to release DGL 0.4  because we have many other features to support (Heterograph, Knowledge Graph, etc.). Before that, user could build DGL from source to use pooling module.

**Comment by xptree** [comment]
@yzh119 Got it. We will check DGL's set2set after the PR is merged. @GuangyongChen Since DGL 0.4 will be released after Alchemy's phase two, we may have to ask contest participants to compile DGL from source rather than install from pip/conda.

**Comment by xptree** [comment]
@GuangyongChen As a complete benchmark, shall we also upload other models that we have implemented? I mean models we reported in our [arXiv paper](https://arxiv.org/abs/1906.09427).

**Comment by yvquanli** [comment]
you can see at this repository of me.
https://github.com/yvquanli/smiles_mol_dataset_in_dgl_styles

**Comment by xptree** [comment]
@yvquanli Thanks! Will definitely refer to. We also put our version at https://github.com/tencent-alchemy/Alchemy/tree/dgl.

**Comment by yvquanli** [comment]
Try this code with parallelism used to speed up the dataset load

```
    def _single_sdf_graph_reader(self, sdf_file):
        result = self.sdf_graph_reader(sdf_file)
        if result is None:
            return (None, None)
        return result

    def _load(self):
        if self.mode == 'dev':
            target_file = pathlib.Path(self.file_dir, "train.csv")
            self.target = pd.read_csv(target_file,
                                      index_col=0,
                                      usecols=[
                                                  'gdb_idx',
                                              ] +
                                              ['property_%d' % x for x in range(12)])
            self.target = self.target[['property_%d' % x for x in range(12)]]

        sdf_dir = pathlib.Path(self.file_dir, "sdf")
        self.graphs, self.labels = [], []
        #         cnt = 0
        #         from tqdm import tqdm
        #         for sdf_file in tqdm(sdf_dir.glob("**/*.sdf")):
        #             result = self.sdf_graph_reader(sdf_file)
        #             if result is None:
        #                 continue
        #             cnt += 1
        #             self.graphs.append(result[0])
        #             self.labels.append(result[1])
        from multiprocessing import Pool
        with Pool() as pool:
            results = pool.map(self._single_sdf_graph_reader, sdf_dir.glob("**/*.sdf"))

        self.graphs, self.labels = list(zip(*results))
        self.normalize()
        print(len(self.graphs), "loaded!")
```

**Comment by mufeili** [comment]
In case you are interested, here is another code example for converting smiles to `DGLGraph`: https://gist.github.com/mufeili/8eb0c1cdf23604e7da7445c49a33676a. Comparing to @yvquanli 's great example, this one does not need networkx for intermediate.

**Comment by geekinglcq** [comment]
> you can see at this repository of me.
> https://github.com/yvquanli/smiles_mol_dataset_in_dgl_styles

Thank you for contribution. 
BTW, I found you have post a multiprocessing dataloader.
Could @Moxinlin please theck the following code and update it?
```py
    def _single_sdf_graph_reader(self, sdf_file):
        result = self.sdf_graph_reader(sdf_file)
        if result is None:
            return (None, None)
        return result

    def _load(self):
        if self.mode == 'dev':
            target_file = pathlib.Path(self.file_dir, "train.csv")
            self.target = pd.read_csv(target_file,
                                      index_col=0,
                                      usecols=[
                                                  'gdb_idx',
                                              ] +
                                              ['property_%d' % x for x in range(12)])
            self.target = self.target[['property_%d' % x for x in range(12)]]

        sdf_dir = pathlib.Path(self.file_dir, "sdf")
        self.graphs, self.labels = [], []
        #         cnt = 0
        #         from tqdm import tqdm
        #         for sdf_file in tqdm(sdf_dir.glob("**/*.sdf")):
        #             result = self.sdf_graph_reader(sdf_file)
        #             if result is None:
        #                 continue
        #             cnt += 1
        #             self.graphs.append(result[0])
        #             self.labels.append(result[1])
        from multiprocessing import Pool
        with Pool() as pool:
            results = pool.map(self._single_sdf_graph_reader, sdf_dir.glob("**/*.sdf"))

        self.graphs, self.labels = list(zip(*results))
        self.normalize()
        print(len(self.graphs), "loaded!")

```

**Comment by xptree** [comment]
@GuangyongChen would you mind completing the README? Add document about DGL.

**Comment by GuangyongChen** [comment]
@xptree No problem, we will revise the README, which can be done by next week.

**Comment by GuangyongChen** [comment]
Hi @xptree , @geekinglcq just revised the README file to add some document about DGL, which can be checked for your reference.

**Comment by xptree** [comment]
@GuangyongChen It seems that we have completed all features described in this issue. Shall we close this issue?

**Comment by GuangyongChen** [comment]
@xptree Thanks for your reminder, I will close this issue.
